[colors.cursor]
cursor = "#47BAC0"
text = "#47BAC0"

[colors.normal]
black = "#212121"
blue = "#949494"
cyan = "#949494"
green = "#ffffff"
magenta = "#ffffff"
red = "#E4609B"
white = "#ffffff"
yellow = "#949494"

[colors.primary]
background = "#18181A"
foreground = "#d5d5d5"
